image: golang:1.8
stages:
  - build
  - test

before_script:
  - ls -la

build_hello:
  script:
    - ls -la
    - pwd && go build
  stage: build
  artifacts:
    paths:
      - helloworld


test:
  script:
    - go test -v
  stage: test