image: golang:1.8
stages:
  - build
  - test

artifacts:
  paths:
    - helloworld

before_script:
  - ls -la

build_hello:
  script:
    - ls -la
    - pwd && go build
  stage: build

test:
  script:
    - go test -v
  stage: test